//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public System.Guid ApplicationId { get; set; }
        public System.Guid CustomerId { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public string ApplicationStatus { get; set; }
    }
}
