//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiApp01
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustAddress
    {
        public System.Guid CustomerId { get; set; }
        public System.Guid AddressId { get; set; }
        public int CustAddressId { get; set; }
    }
}
